version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: swift-codes-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./backend/src/main/resources/Interns_2025_SWIFT_CODES.xlsx:/app/src/main/resources/Interns_2025_SWIFT_CODES.xlsx
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: swift-codes-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:6.0
    container_name: swift-codes-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=swiftcodes
    command: mongod --logpath=/dev/null # Reduce MongoDB logging noise
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/swiftcodes --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongodb_data:
    name: swift-codes-mongodb-data

networks:
  default:
    name: swift-codes-network 